#!/bin/bash
#Christopher Cui 260867703

#Checks the amoutn of arguements and exits if invalid

if [[ $# -ne 2 ]] 
then
	echo "Error: Wrong number of arguments. Please type ./mkproj ARGUMENT OWNER. The argument is the name of the project. The OWNER is the user name the project belongs to."
exit 1
fi


#if projects directory doesnt exist then create it

if [ ! -d "Projects" ]
then
mkdir Projects
fi
cd ./Projects

#if project already exists then exit

if [ -d $1 ]
then
echo "Error: The project name has already been used. Please select another project name and try again."

exit 1

fi
#create project doesnt exist
echo "There was no $1, so creating now"


mkdir $1
cd $1
#1 create subfolders inside of projects
mkdir archive backup docs assets database source
ls
cd docs
#create the readme log and append the message to it
touch readme.txt
echo "Created by: $2"  >> readme.txt 
cat readme.txt



